# Generated by Django 4.2.2 on 2023-06-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employer_company_alter_employer_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employer', 'Employer'), ('freelancer', 'Freelancer')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
