# Generated by Django 4.2.2 on 2023-06-21 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='website',
        ),
        migrations.DeleteModel(
            name='Freelancer',
        ),
    ]
