# Generated by Django 4.2.2 on 2023-06-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='slug',
        ),
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('FULLTIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('FREELANCER', 'Freelancer'), ('INTERNSHIP', 'Internship'), ('TEMPORARY', 'Temporary')], default='FREELANCER', max_length=20, verbose_name='Job type'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
