# Generated by Django 4.2.2 on 2023-06-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_job_slug_job_type_delete_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('ACCOUNTING_AND_FINANCE', 'Accounting and Finance'), ('CLERICAL_&_DATA_ENTRY', 'Clerical & Data Entry'), ('COUNSELING', 'Counseling'), ('COURT_ADMINISTRATION', 'Court Administration'), ('HUMAN_RESOURCES', 'Human Resources'), ('INVESRIGATIVE', 'Investigative'), ('IT_AND_COMPUTERS', 'IT and Computers'), ('LAW_ENFORCEMENT', 'Law Enforcement'), ('MANAGEMENT', 'Management'), ('PUBLIC_RELATIONS', 'Public Relations')], default='ACCOUNTING_AND_FINANCE', max_length=50, verbose_name='Job category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
