# Generated by Django 4.2.2 on 2023-06-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_job_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='budget',
            field=models.PositiveSmallIntegerField(choices=[(1, '0 - 5 000'), (2, '5 000 - 10000'), (3, '10000 - 100000'), (4, '+100 000')], default=1, verbose_name='Type de commande'),
        ),
    ]
