# Generated by Django 4.2.2 on 2023-06-26 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
    ]
