# Generated by Django 4.1.7 on 2023-03-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employer",
            name="company",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="employer",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name=""),
        ),
    ]
