# Generated by Django 4.1.7 on 2023-03-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="slug",
            field=models.CharField(default=1, max_length=150, verbose_name="job url"),
            preserve_default=False,
        ),
    ]
