# Generated by Django 4.1.7 on 2023-03-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_application_applicant_alter_application_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="expiration",
            field=models.DateField(blank=True, null=True),
        ),
    ]
